name: Test Conda Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
        auto-update-conda: true

    - name: Free up disk space
      run: |
        bash .github/workflows/free_disk_space.sh

    - name: Run Conda Server Setup
      shell: bash -l {0}
      run: |
        bash ./setup_scripts/conda_server.sh --light-mode --no-tests